name: memgraph_replay
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.10
  
  # Core dependencies (install via pip for better compatibility)
  - pip
  
  # System dependencies (cross-platform)
  - cmake           # For building some packages
  - make            # Build tool
  
  # Conda packages (prefer conda when available)
  - numpy>=1.24.0
  - pandas>=2.0.0
  
  # Pip dependencies
  - pip:
    # Database connectivity
    - pymgclient>=1.5.0                  # Memgraph Python client (official package)
    
    # Message bus connectivity  
    - nats-py>=2.0.0                     # NATS async client for Python
    
    # JSON processing (high performance)
    - orjson>=3.9.0                      # Fast JSON library
    
    # Data validation and serialization
    - pydantic>=2.0.0                    # Data validation and settings management
    
    # Retry and resilience
    - tenacity>=8.0.0                    # Retry library with exponential backoff
    
    # Filtering and signal processing
    - filterpy>=1.4.5                   # Kalman filtering and signal processing
    
    # Standard library extensions
    - typing-extensions>=4.0.0           # Enhanced typing support
    
    # Development and testing
    - pytest>=7.0.0                      # Testing framework
    - pytest-asyncio>=0.21.0             # Async testing support
    
    # Performance monitoring and utilities
    - psutil>=5.9.0                      # System and process utilities
